### ISSUE TITLE
Read event command not working as expected.

### ISSUE THREAD

**Issue by Arshad-02** [Arshad-02/DiscordBot#1]
line 475, when called, re also responds to other words which starts with re like read,reply etc...It was intended to respond to messages which only have two alphabets "re".

**Comment by ShootGan** [comment]
can you assign me to this?

**Comment by Arshad-02** [comment]
I checked your version, It won't work

**Comment by ShootGan** [comment]
It's doen't react on this comman or what happend?

**Comment by kannangr21** [comment]
Hello,
This issue is also found in de & ae. Assign me this issue and I'll fix this
